name: 07-expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] print start-up data"
        if: ${{ inputs.debug }}
        run: | 
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA commit: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] print when triggered from master"
        if: ${{ inputs.debug && github.ref == 'refs/heads/master' }}
        run: echo "I was triggered form master"
      - name: Greeting
        run: echo "Hello, World!"
